networks:
  default:
    external: true
    name: ${NETWORK:-web}
  net:
    external: true
    name: ${NETWORK:-web}

include:
  - compose/base.yml
  - compose/services.yml
  - compose/apps.yml
  - emqx-docker/docker-compose.yml
  - LibreChat/docker-compose.yml
