version: '3.8'

services:
  streamlit-fin:
    build: 
      context: .
      dockerfile: ./compose/streamlit-fin/Dockerfile
    image: streamlit_fin_local
    container_name: streamlit_fin_app
    restart: always
    ports:
      - 8501:8501
    command: streamlit run src/app.py