services:
  adguardhome:
    image: adguard/adguardhome
    volumes:
      - /var/data/adguardhome_conf:/opt/adguardhome/conf
      - /var/data/adguardhome_work:/opt/adguardhome/work
    # ports:
      # DNS
        # - 53:53
        # # DHCP server
        # - 67:67/udp
        # - 68:68/udp
        # # HTTPS/DNS-over-HTTPS
        # - 443:443/tcp
        # # DNS-over-TLS
        # - 853:853/tcp
        # # DNS-over-QUIC
        # - 853:853/udp
        # # DNSCrypt
        # - 5443:5443/tcp
        # - 5443:5443/udp
        # # WebUI
        # - 3000:3000/tcp
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.tcp.routers.adguardhome_tcp.entrypoints=dns
        - traefik.tcp.routers.adguardhome_tcp.rule=HostSNI(`*`)
        - traefik.tcp.routers.adguardhome_tcp.service=adguardhome_dns_service
        - traefik.tcp.services.adguardhome_dns_service.loadbalancer.server.port=53
        - traefik.http.routers.adguardhome.entrypoints=https
        - traefik.http.routers.adguardhome.rule=Host(`guard.${DOMAIN}`)
        - traefik.http.routers.adguardhome.tls.certresolver=le
        - traefik.http.routers.adguardhome.service=adguardhome_service
        - traefik.http.services.adguardhome_service.loadbalancer.server.port=3000

networks:
  traefik-public:
    external: true