apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f services.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: dozzle
    traefik.constraint-label: traefik-public
    traefik.swarm.network: traefik-public
    traefik.enable: "true"
    traefik.http.routers.dozzle.entrypoints: https
    traefik.http.routers.dozzle.middlewares: admin-auth
    traefik.http.routers.dozzle.rule: Host(`log.`)
    traefik.http.routers.dozzle.service: dozzle_service
    traefik.http.routers.dozzle.tls.certresolver: le
    traefik.http.services.dozzle_service.loadbalancer.server.port: "8080"
  name: dozzle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dozzle
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f services.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: dozzle
    spec:
      containers:
        - env:
            - name: DOMAIN
          image: amir20/dozzle:latest
          name: dozzle
      restartPolicy: Always
