services:
  emqx1:
    image: emqx:latest
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 60s
      timeout: 25s
      retries: 5
    networks:
      - traefik-public
    ports:
      - "1883:1883"
    #   - 8083:8083
    #   - 8084:8084
    #   - 8883:8883
    #   - 18083:18083
    volumes:
      - emqx-data1:/opt/emqx/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.emqx1.entrypoints=web-secure"
        - "traefik.http.routers.emqx1.rule=Host(`mqtt.${DOMAINNAME}`)"
        - "traefik.http.routers.emqx1.tls.certresolver=letsencrypt"
        - "traefik.http.routers.emqx1.service=emqx-dashboard"
        - "traefik.http.services.emqx-dashboard.loadbalancer.server.port=18083"

  mqttx-web:
    image: emqx/mqttx-web:latest
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mqttx-web.entrypoints=web-secure"
        - "traefik.http.routers.mqttx-web.rule=Host(`mqttx.${DOMAINNAME}`)"
        - "traefik.http.routers.mqttx-web.tls.certresolver=letsencrypt"
        - "traefik.http.routers.mqttx-web.service=mqttx-web-service"
        - "traefik.http.services.mqttx-web-service.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true

volumes:
  emqx-data1:
    driver: local
