apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f services.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: minio-common
    traefik.constraint-label: traefik-public
    traefik.docker.network: traefik-public
    traefik.enable: "true"
    traefik.http.routers.minio-api-router.entrypoints: https
    traefik.http.routers.minio-api-router.rule: Host(`minio.`) || Host(`s3.`)
    traefik.http.routers.minio-api-router.service: minio_api_service
    traefik.http.routers.minio-api-router.tls.certresolver: le
    traefik.http.routers.minio-router.entrypoints: https
    traefik.http.routers.minio-router.rule: Host(`drive.`) || Host(`storage.`)
    traefik.http.routers.minio-router.service: minio_common_service
    traefik.http.routers.minio-router.tls.certresolver: le
    traefik.http.services.minio_api_service.loadbalancer.server.port: "9000"
    traefik.http.services.minio_common_service.loadbalancer.server.port: "9001"
  name: minio-common
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio-common
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f services.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: minio-common
    spec:
      containers:
        - args:
            - server
            - /data
            - --address
            - :9000
            - --console-address
            - :9001
          env:
            - name: DOMAIN
            - name: MINIO_OPTS
              value: --console-address :9001
            - name: MINIO_ROOT_PASSWORD
              value: minioadmin
            - name: MINIO_ROOT_USER
              value: minioadmin
            - name: MINIO_SERVER_URL
              value: https://minio.
          image: minio/minio:latest
          livenessProbe:
            exec:
              command:
                - mc
                - ready
                - local
            failureThreshold: 5
            periodSeconds: 60
            timeoutSeconds: 5
          name: minio-common
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: minio-common-claim0
      restartPolicy: Always
      volumes:
        - name: minio-common-claim0
          persistentVolumeClaim:
            claimName: minio-common-claim0
