networks:
  traefik-public:
    external: true

services:
  open_webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    environment:
      - DOMAIN=${DOMAIN}
      - PORT=${OPEN_WEBUI_PORT:-8080}
      - WEBUI_URL=http://localhost:${OPEN_WEBUI_PORT:-8080}
      - ENABLE_OLLAMA_API=${ENABLE_OLLAMA_API:-false}
    volumes:
      - /var/data/open-webui:/app/backend/data
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.open_webui.entrypoints=https
        - traefik.http.routers.open_webui.rule=Host(`bot.${DOMAIN}`)
        - traefik.http.routers.open_webui.tls.certresolver=le
        - traefik.http.routers.open_webui.service=open_webui_app
        - traefik.http.services.open_webui_app.loadbalancer.server.port=${OPEN_WEBUI_PORT:-8080}
