networks:
  traefik-public:
    external: true

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    environment:
      - DOMAIN=${DOMAIN}
      - OPEN_WEBUI_PORT=${OPEN_WEBUI_PORT-8080}
      - ENABLE_OLLAMA_API=${ENABLE_OLLAMA_API-false}
    volumes:
      - /var/data/open-webui:/app/backend/data
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.open-webui.entrypoints=https
        - traefik.http.routers.open-webui.rule=Host(`bot.${DOMAIN}`)
        - traefik.http.routers.open-webui.tls.certresolver=le
        - traefik.http.routers.open-webui.service=open-webui_app
        - traefik.http.services.open-webui_app.loadbalancer.server.port=${OPEN_WEBUI_PORT:-8080}
