networks:
  traefik-public:
    external: true

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - /var/data/open-webui:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.open-webui.entrypoints=https
        - traefik.http.routers.open-webui.rule=Host(`bot.${DOMAIN}`)
        - traefik.http.routers.open-webui.tls.certresolver=le
        - traefik.http.routers.open-webui.service=open-webui
        - traefik.http.services.open-webui.loadbalancer.server.port=${OPEN_WEBUI_PORT-8080}
