apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f services.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: osrm-backend
    traefik.constraint-label: traefik-public
    traefik.docker.network: traefik-public
    traefik.enable: "true"
    traefik.http.routers.osrm-backend.entrypoints: https
    traefik.http.routers.osrm-backend.middlewares: rate-limit
    traefik.http.routers.osrm-backend.rule: Host(`osrm.`)
    traefik.http.routers.osrm-backend.service: osrm_backend_service
    traefik.http.routers.osrm-backend.tls.certresolver: le
    traefik.http.services.osrm_backend_service.loadbalancer.server.port: "5000"
  name: osrm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: osrm-backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f services.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: osrm-backend
    spec:
      containers:
        - env:
            - name: DOMAIN
            - name: OSRM_ALGORITHM
              value: mld
            - name: OSRM_GEOFABRIK_PATH
            - name: OSRM_MAP_NAME
            - name: OSRM_NOTIFY_FILEPATH
              value: /data/osrm_notify.txt
            - name: OSRM_PORT
              value: "5000"
            - name: OSRM_PROFILE
              value: /opt/car.lua
            - name: OSRM_THREADS
              value: "2"
          image: furyhawk/osrm-backend:latest
          name: osrm-backend
      restartPolicy: Always
