apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f searxng.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: redis-valkey
  name: redis-valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-valkey
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f searxng.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: redis-valkey
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: searxng.redis
                    operator: In
                    values:
                      - "true"
      containers:
        - args:
            - valkey-server
            - --save
            - "30"
            - "1"
            - --loglevel
            - warning
          image: docker.io/valkey/valkey:7-alpine
          name: redis-valkey
          securityContext:
            capabilities:
              add:
                - SETGID
                - SETUID
                - DAC_OVERRIDE
              drop:
                - ALL
          volumeMounts:
            - mountPath: /data
              name: valkey-data2
      restartPolicy: Always
      volumes:
        - name: valkey-data2
          persistentVolumeClaim:
            claimName: valkey-data2
