apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f searxng.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: searxng
    traefik.constraint-label: traefik-public
    traefik.docker.network: traefik-public
    traefik.enable: "true"
    traefik.http.routers.searxng-rtr.entrypoints: https
    traefik.http.routers.searxng-rtr.middlewares: xbot
    traefik.http.routers.searxng-rtr.rule: Host(`search.`)
    traefik.http.routers.searxng-rtr.service: searxng-svc
    traefik.http.routers.searxng-rtr.tls.certresolver: le
    traefik.http.services.searxng-svc.loadbalancer.server.port: "8080"
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: searxng
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f searxng.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: searxng
    spec:
      containers:
        - env:
            - name: LIMITER
              value: "true"
            - name: SEARXNG_BASE_URL
              value: https://search./
            - name: SEARXNG_LIMITER
              value: "true"
            - name: SEARXNG_REDIS_URL
              value: redis://redis_valkey:6379/0
            - name: SEARXNG_SECRET
              value: ultrasecretkey
          image: docker.io/searxng/searxng:latest
          name: searxng
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng-claim0
      restartPolicy: Always
      volumes:
        - name: searxng-claim0
          persistentVolumeClaim:
            claimName: searxng-claim0
