services:

  cyberchef:
    image: mpepping/cyberchef:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.cyberchef.entrypoints=https
        - traefik.http.routers.cyberchef.rule=Host(`chef.${DOMAIN}`) || Host(`cook.${DOMAIN}`)
        - traefik.http.routers.cyberchef.tls.certresolver=le
        - traefik.http.routers.cyberchef.service=cyberchef
        - traefik.http.services.cyberchef.loadbalancer.server.port=8000
    networks:
      - traefik-public

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${DATABASE__PASSWORD}
    volumes:
      - /var/data/config/librespeed:/config
    # ports:
    #   - 80:80
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.librespeed.entrypoints=https
        - traefik.http.routers.librespeed.rule=Host(`speed.${DOMAIN}`) || Host(`speedtest.${DOMAIN}`)
        - traefik.http.routers.librespeed.tls.certresolver=le
        - traefik.http.routers.librespeed.service=librespeed_app
        - traefik.http.services.librespeed_app.loadbalancer.server.port=80

  linx:
    image: andreimarcu/linx-server
    command: -config /linx.conf
    volumes:
      - /var/data/linx/:/files/
      - /var/data/config/linx/linx.conf:/linx.conf:ro
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.linx.entrypoints=https
        - traefik.http.routers.linx.rule=Host(`linx.${DOMAIN}`)
        - traefik.http.routers.linx.tls.certresolver=le
        - traefik.http.routers.linx.service=linx_app
        - traefik.http.services.linx_app.loadbalancer.server.port=8080

    networks:
      - traefik-public
networks:
  traefik-public:
    external: true