services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PASSWORD=${DATABASE__PASSWORD}
    volumes:
      - /var/data/config/librespeed:/config
    # ports:
    #   - 80:80
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.librespeed.entrypoints=https
        - traefik.http.routers.librespeed.rule=Host(`speed.${DOMAIN}`) || Host(`speedtest.${DOMAIN}`)
        - traefik.http.routers.librespeed.tls.certresolver=le
        - traefik.http.routers.librespeed.service=librespeed_app
        - traefik.http.services.librespeed_app.loadbalancer.server.port=80

  cyberchef:
    image: ghcr.io/gchq/cyberchef:latest
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.cyberchef.entrypoints=https
        - traefik.http.routers.cyberchef.rule=Host(`chef.${DOMAIN}`) || Host(`cook.${DOMAIN}`)
        - traefik.http.routers.librespeed.tls.certresolver=le
        - traefik.http.routers.cyberchef.service=cyberchef
        - traefik.http.services.cyberchef.loadbalancer.server.port=80
    networks:
      - traefik_public

networks:
  traefik-public:
    external: true