services:
  thelounge:
    image: thelounge/thelounge:latest
    volumes:
      - /var/data/thelounge-data:/var/opt/thelounge
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.thelounge-https.entrypoints=https
        - traefik.http.routers.thelounge-https.rule=Host(`irc.${DOMAIN?Variable not set}`)
        - traefik.http.routers.thelounge-https.tls.certresolver=le
        - traefik.http.services.thelounge.loadbalancer.server.port=9000

networks:
  traefik-public:
    external: true
