apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: valkey-data2
  name: valkey-data2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
