http:
  routers:
    traefik-public-https:
      entryPoints:
        - https
      rule: Host(`coco.cloudy.local`)
      middlewares:
        - admin-auth@swarm
      tls: {}
      service: coco_desktop@file

  services:

    coco_desktop:
      loadBalancer:
        servers:
          - url: http://192.168.50.178:5000
