http:
  serversTransports:
    pvetransport:
      insecureSkipVerify: true

  routers:
    local-traefik-public-https:
      entryPoints:
        - https
      rule: Host(`coco.swarm.local`)
      middlewares:
        - admin-auth@swarm
      tls: {}
      service: coco_desktop@file

    local-proxmox00:
      entryPoints:
        - https
      rule: Host(`dc00.swarm.local`)
      tls: {}
      service: proxmox00@file

    local-proxmox01:
      entryPoints:
        - https
      rule: Host(`dc01.swarm.local`)
      tls: {}
      service: proxmox01@file

    traefik-public-https:
      entryPoints:
        - https
      rule: Host(`coco.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls:
        certResolver: le
      service: coco_desktop@file

    proxmox00:
      entryPoints:
        - https
      rule: Host(`dc00.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls: {}
      service: proxmox00@file

    proxmox01:
      entryPoints:
        - https
      rule: Host(`dc01.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls: {}
      service: proxmox01@file

  services:
    coco_desktop:
      loadBalancer:
        servers:
          - url: "http://192.168.50.178:5000"

    proxmox00:
      loadBalancer:
        passHostHeader: true
        serversTransport: "pvetransport"
        servers:
          - url: "https://192.168.50.210:8006"

    proxmox01:
      loadBalancer:
        passHostHeader: true
        serversTransport: "pvetransport"
        servers:
          - url: "https://192.168.50.210:8006"

tcp:
  routers:
    spice:
      entryPoints:
        - spice
      rule: HostSNI(`*`)
      tls: false
      service: spice@file
    spice-tls:
      entryPoints:
        - spice-tls
      rule: HostSNI(`*`)
      tls:
        passthrough: true
      service: spice-tls@file

  services:
    spice:
      loadBalancer:
        servers:
          - address: "https://192.168.50.210:3128"
    spice-tls:
      loadBalancer:
        servers:
          - address: "https://192.168.50.210:61000"
