http:
  routers:
    local-traefik-public-https:
      entryPoints:
        - https
      rule: Host(`coco.swarm.local`)
      middlewares:
        - admin-auth@swarm
      tls:
        passthrough: true
      service: coco_desktop@file
    
    local-proxmox00:
      entryPoints:
        - https
      rule: Host(`proxmox00.swarm.local`)
      tls: {}
      service: proxmox00@file

    local-proxmox01:
      entryPoints:
        - https
      rule: Host(`proxmox01.swarm.local`)
      tls:
        passthrough: true
      service: proxmox01@file

    traefik-public-https:
      entryPoints:
        - https
      rule: Host(`coco.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls:
        certResolver: le
      service: coco_desktop@file

    proxmox00:
      entryPoints:
        - https
      rule: Host(`proxmox00.furyhawk.lol`)
      tls:
        passthrough: true
      service: proxmox00@file

    proxmox01:
      entryPoints:
        - https
      rule: Host(`proxmox01.furyhawk.lol`)
      tls:
        passthrough: true
      service: proxmox01@file

  services:

    coco_desktop:
      loadBalancer:
        servers:
          - url: http://192.168.50.178:5000

    proxmox00:
      loadBalancer:
        servers:
          - url: https://192.168.50.210:8006

    proxmox01:
      loadBalancer:
        servers:
          - url: https://192.168.50.201:8006
