http:
  routers:
    traefik-public-https:
      entryPoints:
        - https
      rule: Host(`coco.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls:
        certResolver: le
      service: coco_desktop@file

    pi_hole:
      entryPoints:
        - https
      rule: Host(`pihole.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls:
        certResolver: le
      service: pi_hole@file

    dev_machine:
      entryPoints:
        - https
      rule: Host(`dev.furyhawk.lol`) || Host(`staging.furyhawk.lol`) || Host(`prod.furyhawk.lol`)
      tls:
        certResolver: le
      service: dev_machine@file

    service_machine:
      entryPoints:
        - https
      rule: Host(`service.furyhawk.lol`)
      tls:
        certResolver: le
      service: service_machine@file

    mail_machine:
      entryPoints:
        - https
      rule: Host(`mail.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls:
        certResolver: le
      service: mail_machine@file

    proxmox00:
      entryPoints:
        - https
      rule: Host(`proxmox00.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls:
        certResolver: le
      service: proxmox00@file

    proxmox01:
      entryPoints:
        - https
      rule: Host(`proxmox01.furyhawk.lol`)
      middlewares:
        - admin-auth@swarm
      tls:
        certResolver: le
      service: proxmox01@file

  services:

    coco_desktop:
      loadBalancer:
        servers:
          - url: http://192.168.50.178:5000

    proxmox00:
      loadBalancer:
        servers:
          - url: https://192.168.50.210:8006

    proxmox01:
      loadBalancer:
        servers:
          - url: https://192.168.50.201:8006

    pi_hole:
      loadBalancer:
        servers:
          - url: http://192.168.50.155

    dev_machine:
      loadBalancer:
        servers:
          - url: http://192.168.50.44:5173

    service_machine:
      loadBalancer:
        servers:
          - url: http://192.168.50.44:8000

    mail_machine:
      loadBalancer:
        servers:
          - url: http://192.168.50.44:1080