---
- name: Playbook
  hosts: all
  become: true

  vars:
    omz_install_zsh: true
    users:
      - name: "user"
        group: "user"
        settings: ""
  tasks:
    - name: Run ansible-role-oh-my-zsh.
      include_role:
        name: "ctorgalson.oh-my-zsh"
      vars:
        omz_user: "{{ item }}"
        # Only create `.zshrc` for user 'user'; item.settings will be
        # appended to `.zshrc` for the user 'user'.
        omz_zshrc_create: "{{ (item.name == 'user') | ternary(true, false) }}"
        omz_plugins:
          - "kubectl"
          - "git"
      with_items: "{{ users }}"