os: "linux"
arch: "amd64"

talos_version: v1.7.0
talosctl_version: v1.7.5
control_plane_ip: 192.168.50.195

control_plane_2: 192.168.50.196
control_plane_3: 192.168.50.197

worker_1: 192.168.50.198
worker_2: 192.168.50.199

config_directory: "/home/{{ ansible_user }}/.talos"
config_file: "/home/{{ ansible_user }}/.talos/talosconfig"

kube_vip_version: "v0.8.0"
vip_interface: null
vip: 192.168.50.220

metallb_version: v0.13.12
lb_range: 192.168.50.240-192.168.50.250
lb_pool_name: first-pool

ansible_user: ubuntu
ansible_become: true
ansible_become_method: sudo
