./vackup.sh import core_traefik-public-certificates.tar.gz core_traefik-public-certificates
./vackup.sh import apps_jellyfin_config.tar.gz apps_jellyfin_config
./vackup.sh import docmost_docmost_redis_data.tar.gz docmost_docmost_redis_data
./vackup.sh import openwebui_open_webui.tar.gz openwebui_open_webui
./vackup.sh import outline_outline_redis_data.tar.gz outline_outline_redis_data
./vackup.sh import portainer_portainer-data.tar.gz portainer_portainer-data
./vackup.sh import searxng_searxng_data.tar.gz searxng_searxng_data
./vackup.sh import searxng_valkey_data2.tar.gz searxng_valkey_data2
./vackup.sh import services_postgres_data.tar.gz services_postgres_data