devservers:
  hosts:
    node09:
      ansible_host: 101.100.172.55
      ansible_port: 9991
    node00:
      ansible_host: 101.100.172.55
      ansible_port: 9999
    node01:
      ansible_host: 101.100.172.55
      ansible_port: 9998

debian:
  hosts:
    node00:
      ansible_host: 101.100.172.55
      ansible_port: 9999
    node01:
      ansible_host: 101.100.172.55
      ansible_port: 9998

local:
  hosts:
    node00:
      ansible_host: 192.168.50.114
      ansible_port: 22
    node01:
      ansible_host: 192.168.50.68
      ansible_port: 22
    node02:
      ansible_host: 192.168.50.56
      ansible_port: 22

test:
  hosts:
    node05:
      ansible_host: 192.168.50.205
      ansible_port: 22
    node09:
      ansible_host: 192.168.50.209
      ansible_port: 22
