## File values.yaml ##
providers:
  # Disable the Ingress provider (optional)
  # We do not want to use Ingress objects anymore!
  kubernetesIngress:
    enabled: false
  # Enable the GatewayAPI provider
  kubernetesGateway:
    enabled: true
# Allow the Gateway to expose HTTPRoute from all namespaces
# Allow the Gateway to expose HTTPRoute from all namespaces
gateway:
  listeners:
    web:
      namespacePolicy: All
    websecure:
      namespacePolicy: All

  # annotations:
  #   cert-manager.io/issuer: selfsigned-issuer
  # listeners:
  #   websecure:
  #     hostname: whoami.localhost
  #     certificateRefs:
  #       - name: whoami-tls